const ProjectDescriptionStatic = () => {
  // Example static project data
  const project = {
    title: "Solar Farm Project Alpha",
    image:
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    overview: `WI IPP aims to make renewable energy through photovoltaic and wind energy systems the standard. The focus is on systems with repowering potential in order to convert existing systems to the latest technologies and enable more efficient power generation.

The companies in which WI IPP has a stake already operate several wind and solar parks whose output is sufficient to supply more than 45,500 households with green electricity and save around 75,000 tons of CO₂ annually.

WI IPP is currently planning to expand its solar portfolio with new projects. These include a PV open-space system in Forstinning and several PV roof systems in Forstorf, Aeroclub Koblenz and Oschersleben. These projects will help to further expand sustainable energy production and actively drive forward the energy transition.

As a holistically oriented company, WI IPP is committed to enabling people to share in the prosperity generated by the electrical energy produced. For this reason, WI IPP enables both institutional investors and targeted crowd investors to participate in the financing of projects. Several project companies have already successfully implemented wind and solar projects with WIWIN to enable citizen participation.`,
    entrepreneur: `WI IPP aims to make renewable energy through photovoltaic and wind energy systems the standard. The focus is on systems with repowering potential in order to convert existing systems to the latest technologies and enable more efficient power generation.

The companies in which WI IPP has a stake already operate several wind and solar parks whose output is sufficient to supply more than 45,500 households with green electricity and save around 75,000 tons of CO₂ annually.`,
    stats: {
      fundType: "Donation",
      daysLeft: 50,
      impactScore: 92,
      fundingGoal: "$20,000",
      fundingAcquired: "90%",
    },
  };

  return (
    <div className="min-h-screen bg-gray-100 py-8">
      <div className="container mx-auto px-4 grid grid-cols-1 lg:grid-cols-4 gap-8">
        {/* Left Section - Project Details */}
        <div className="lg:col-span-3 bg-white shadow-md rounded-lg overflow-hidden">
          {/* Title */}
          <h2 className="text-xl font-semibold px-6 py-4 border-b border-gray-200">
            {project.title}
          </h2>

          {/* Image */}
          <img
            src={project.image}
            alt={project.title}
            className="w-full h-72 object-cover"
          />

          {/* Overview */}
          <div className="p-6">
            <h3 className="text-lg font-semibold mb-2">Project Overview</h3>
            <p className="text-gray-700 whitespace-pre-line">
              {project.overview}
            </p>
          </div>

          {/* Entrepreneur */}
          <div className="p-6 border-t border-gray-200">
            <h3 className="text-lg font-semibold mb-2">About the Entrepreneur</h3>
            <p className="text-gray-700 whitespace-pre-line">
              {project.entrepreneur}
            </p>
          </div>
        </div>

        {/* Right Section - Sidebar Stats */}
        <div className="space-y-4">
          <button className="w-full bg-slate-800 text-white py-3 rounded-md font-medium">
            Back this Project
          </button>

          <div className="bg-white rounded-lg shadow p-4 space-y-3">
            <div className="flex justify-between border-b pb-2">
              <span className="text-gray-600 text-sm">Funding Type</span>
              <span className="font-medium">{project.stats.fundType}</span>
            </div>
            <div className="flex justify-between border-b pb-2">
              <span className="text-gray-600 text-sm">Days Left</span>
              <span className="font-medium">{project.stats.daysLeft}</span>
            </div>
            <div className="flex justify-between border-b pb-2">
              <span className="text-gray-600 text-sm">Impact Score</span>
              <span className="font-medium">{project.stats.impactScore}</span>
            </div>
            <div className="flex justify-between border-b pb-2">
              <span className="text-gray-600 text-sm">Funding Goal</span>
              <span className="font-medium">{project.stats.fundingGoal}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-600 text-sm">Funding Acquired</span>
              <span className="font-medium">{project.stats.fundingAcquired}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProjectDescriptionStatic;
